---
- name: Watching for Problems on Dynatrace
  hosts: all
  sources:
    - dynatrace.event_driven_ansible.dt_esa_api:
        dt_api_host: "{{ dynatrace_host }}"
        dt_api_token: "{{ dynatrace_token }}"
        delay: "{{ dynatrace_delay }}"

  rules:
    - name: Look for open Synthetic monitor problem
      condition: 
        all:
          - event.title contains "Multiple synthetic problems"
      action:
        run_job_template:
          name: Restart Nginx
          organization: "Default"
      #condition:
      #  all:
      #    - event.status == "OPEN"
