---
- name: Web Site Checks Rulebook
  hosts: all
  
  sources:
    - name: Are my web sites operational
      ansible.eda.url_check:
        verify_ssl: false
        delay: 10 # seconds
        urls:
          - http://test1.thatcigardude.com
#
# How to easily debug output (to get event metadata for instance)
#
#  rules:
#    - name: Debug output
#      condition: event.url_check.status == "down"
#      action:
#        debug:

  rules:
    - name: "Alert if URL is down (call AAP controller)"
      condition:
        any:
          - event.url_check.status == "down"
      throttle:
        once_within: 2 minutes
        group_by_attributes:
          - event.url_check.url
      action:
        run_job_template:
          name: "web_fix"
          organization: "Default"
#          # Need JT prompt-on-launch for the below to work!
#          job_args:
#            extra_vars:
#              website: '{{ event.url_check.url }}'