---
- name: Restore nginx service 
  hosts: "{{ reporting_host }}"
  gather_facts: false
  become: true
  tasks:

    - name: Try to restart nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
      register: chksrvc

    - name: Print chksrvc
      ansible.builtin.debug:
        msg: "Hey your nginix web server is back up. Good for you"
      when: chksrvc.state == "started"
      
