---
- name: Restore Service
  hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: Restart Nginx
      ansible.builtin.debug:
        msg: "Restarting Nginx Webserver!"

    - name: Restart Web Server
      ansible.builtin.service:
        name: nginx
        state: restarted
